version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file: .env.prod
    volumes:
      - static_data:/app/static
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`coldplaymeetup.tk`)"

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

  traefik:
    image: traefik:v2.5
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "acme:/letsencrypt"

volumes:
  static_data:
  redis_data:
  acme:
